import '../../core/enums/container_size.dart';
import '../../core/enums/driver_status.dart';
import '../../core/enums/location_type.dart';
import '../../core/enums/port_cfs_type.dart';
import '../../core/enums/shipment_type.dart';
import '../../core/enums/transport_status.dart';
import '../../core/enums/vehicle_status.dart';
import '../../features/drivers/domain/driver_model.dart';
import '../../features/locations/domain/location_model.dart';
import '../../features/parties/domain/party_model.dart';
import '../../features/ports_cfs/domain/port_cfs_model.dart';
import '../../features/shipping_lines/domain/shipping_line_model.dart';
import '../../features/transport/domain/activity_log.dart';
import '../../features/transport/domain/notification_log.dart';
import '../../features/transport/domain/pod_document.dart';
import '../../features/transport/domain/transport_model.dart';
import '../../features/vehicles/domain/vehicle_model.dart';

class DemoSeedData {
  static List<Vehicle> getVehicles() {
    final now = DateTime.now();
    return [
      Vehicle(
        id: 'veh-1',
        vehicleNumber: 'MH12AB1234',
        vehicleType: 'Trailer',
        capacity: '40 FT',
        status: VehicleStatus.onTrip,
        assignedDriverId: 'drv-1',
        assignedDriverName: 'Ravi Kumar',
        createdAt: now.subtract(const Duration(days: 90)),
      ),
      Vehicle(
        id: 'veh-2',
        vehicleNumber: 'MH14CD5678',
        vehicleType: 'Container Truck',
        capacity: '20 FT',
        status: VehicleStatus.available,
        createdAt: now.subtract(const Duration(days: 80)),
      ),
      Vehicle(
        id: 'veh-3',
        vehicleNumber: 'MH04EF9012',
        vehicleType: 'Trailer',
        capacity: '40 FT',
        status: VehicleStatus.available,
        createdAt: now.subtract(const Duration(days: 75)),
      ),
      Vehicle(
        id: 'veh-4',
        vehicleNumber: 'MH48GH3456',
        vehicleType: 'Multi-Axle',
        capacity: '40 FT',
        status: VehicleStatus.onTrip,
        assignedDriverId: 'drv-4',
        assignedDriverName: 'Rahul More',
        createdAt: now.subtract(const Duration(days: 60)),
      ),
      Vehicle(
        id: 'veh-5',
        vehicleNumber: 'MH43JK7890',
        vehicleType: 'Trailer',
        capacity: '40 FT',
        status: VehicleStatus.maintenance,
        createdAt: now.subtract(const Duration(days: 50)),
      ),
      Vehicle(
        id: 'veh-6',
        vehicleNumber: 'MH01LM2345',
        vehicleType: 'Truck',
        capacity: '20 FT',
        status: VehicleStatus.available,
        createdAt: now.subtract(const Duration(days: 45)),
      ),
      Vehicle(
        id: 'veh-7',
        vehicleNumber: 'MH06NP6789',
        vehicleType: 'Trailer',
        capacity: '40 FT',
        status: VehicleStatus.onTrip,
        assignedDriverId: 'drv-5',
        assignedDriverName: 'Vijay Yadav',
        createdAt: now.subtract(const Duration(days: 40)),
      ),
      Vehicle(
        id: 'veh-8',
        vehicleNumber: 'MH46QR0123',
        vehicleType: 'Container Truck',
        capacity: '20 FT',
        status: VehicleStatus.available,
        createdAt: now.subtract(const Duration(days: 35)),
      ),
      Vehicle(
        id: 'veh-9',
        vehicleNumber: 'MH15ST4567',
        vehicleType: 'Trailer',
        capacity: '40 FT',
        status: VehicleStatus.available,
        createdAt: now.subtract(const Duration(days: 30)),
      ),
      Vehicle(
        id: 'veh-10',
        vehicleNumber: 'MH09UV8901',
        vehicleType: 'Multi-Axle',
        capacity: '40 FT',
        status: VehicleStatus.inactive,
        isActive: false,
        createdAt: now.subtract(const Duration(days: 25)),
      ),
      Vehicle(
        id: 'veh-11',
        vehicleNumber: 'MH12WX2345',
        vehicleType: 'Trailer',
        capacity: '40 FT',
        status: VehicleStatus.available,
        createdAt: now.subtract(const Duration(days: 20)),
      ),
      Vehicle(
        id: 'veh-12',
        vehicleNumber: 'MH14YZ6789',
        vehicleType: 'Container Truck',
        capacity: '20 FT',
        status: VehicleStatus.available,
        createdAt: now.subtract(const Duration(days: 15)),
      ),
    ];
  }

  static List<Driver> getDrivers() {
    final now = DateTime.now();
    return [
      Driver(
        id: 'drv-1',
        name: 'Ravi Kumar',
        mobileNumber: '9822012345',
        status: DriverStatus.onTrip,
        currentVehicleId: 'veh-1',
        currentVehicleNumber: 'MH12AB1234',
        createdAt: now.subtract(const Duration(days: 120)),
      ),
      Driver(
        id: 'drv-2',
        name: 'Suresh Patil',
        mobileNumber: '9822198765',
        status: DriverStatus.available,
        createdAt: now.subtract(const Duration(days: 110)),
      ),
      Driver(
        id: 'drv-3',
        name: 'Amit Sharma',
        mobileNumber: '9890145678',
        status: DriverStatus.available,
        createdAt: now.subtract(const Duration(days: 100)),
      ),
      Driver(
        id: 'drv-4',
        name: 'Rahul More',
        mobileNumber: '9765432109',
        status: DriverStatus.onTrip,
        currentVehicleId: 'veh-4',
        currentVehicleNumber: 'MH48GH3456',
        createdAt: now.subtract(const Duration(days: 90)),
      ),
      Driver(
        id: 'drv-5',
        name: 'Vijay Yadav',
        mobileNumber: '9860123456',
        status: DriverStatus.onTrip,
        currentVehicleId: 'veh-7',
        currentVehicleNumber: 'MH06NP6789',
        createdAt: now.subtract(const Duration(days: 80)),
      ),
      Driver(
        id: 'drv-6',
        name: 'Sunil Pawar',
        mobileNumber: '9922876543',
        status: DriverStatus.offDuty,
        createdAt: now.subtract(const Duration(days: 70)),
      ),
      Driver(
        id: 'drv-7',
        name: 'Ganesh Deshmukh',
        mobileNumber: '9823456789',
        status: DriverStatus.available,
        createdAt: now.subtract(const Duration(days: 60)),
      ),
      Driver(
        id: 'drv-8',
        name: 'Deepak Shinde',
        mobileNumber: '9730012345',
        status: DriverStatus.available,
        createdAt: now.subtract(const Duration(days: 50)),
      ),
      Driver(
        id: 'drv-9',
        name: 'Pravin Jadhav',
        mobileNumber: '9881123456',
        status: DriverStatus.available,
        createdAt: now.subtract(const Duration(days: 40)),
      ),
      Driver(
        id: 'drv-10',
        name: 'Santosh Kadam',
        mobileNumber: '9657890123',
        status: DriverStatus.inactive,
        isActive: false,
        createdAt: now.subtract(const Duration(days: 30)),
      ),
      Driver(
        id: 'drv-11',
        name: 'Nitin Sawant',
        mobileNumber: '9821234567',
        status: DriverStatus.available,
        createdAt: now.subtract(const Duration(days: 20)),
      ),
      Driver(
        id: 'drv-12',
        name: 'Manoj Bhosale',
        mobileNumber: '9850123987',
        status: DriverStatus.available,
        createdAt: now.subtract(const Duration(days: 10)),
      ),
    ];
  }

  static List<Party> getParties() {
    final now = DateTime.now();
    return [
      Party(
        id: 'pty-1',
        name: 'ABC Logistics Pvt Ltd',
        mobileNumber: '9822001122',
        email: 'ops@abclogistics.in',
        city: 'Pune',
        createdAt: now.subtract(const Duration(days: 180)),
      ),
      Party(
        id: 'pty-2',
        name: 'XYZ Exports Corp',
        mobileNumber: '9822334455',
        email: 'export@xyzexports.com',
        city: 'Mumbai',
        createdAt: now.subtract(const Duration(days: 150)),
      ),
      Party(
        id: 'pty-3',
        name: 'Global Trading Co.',
        mobileNumber: '9890556677',
        email: 'contact@globaltrade.co',
        city: 'Thane',
        createdAt: now.subtract(const Duration(days: 140)),
      ),
      Party(
        id: 'pty-4',
        name: 'Prime Imports Ltd',
        mobileNumber: '9860889900',
        email: 'clearance@primeimports.com',
        city: 'Navi Mumbai',
        createdAt: now.subtract(const Duration(days: 130)),
      ),
      Party(
        id: 'pty-5',
        name: 'Western Cargo Services',
        mobileNumber: '9765112233',
        email: 'booking@westerncargo.in',
        city: 'Bhiwandi',
        createdAt: now.subtract(const Duration(days: 100)),
      ),
      Party(
        id: 'pty-6',
        name: 'Metro Industries',
        mobileNumber: '9922445566',
        email: 'shipping@metroind.in',
        city: 'Pune',
        createdAt: now.subtract(const Duration(days: 80)),
      ),
      Party(
        id: 'pty-7',
        name: 'Apex Manufacturing Co.',
        mobileNumber: '9823667788',
        email: 'logistics@apexmanuf.com',
        city: 'Panvel',
        createdAt: now.subtract(const Duration(days: 60)),
      ),
      Party(
        id: 'pty-8',
        name: 'Blue Star Freight Forwarders',
        mobileNumber: '9730889911',
        email: 'dispatch@bluestarfreight.com',
        city: 'Mumbai',
        createdAt: now.subtract(const Duration(days: 40)),
      ),
    ];
  }

  static List<ShippingLine> getShippingLines() {
    final now = DateTime.now();
    return [
      ShippingLine(
        id: 'shp-1',
        name: 'MSC',
        code: 'MSCU',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      ShippingLine(
        id: 'shp-2',
        name: 'Maersk',
        code: 'MAEU',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      ShippingLine(
        id: 'shp-3',
        name: 'CMA CGM',
        code: 'CMAU',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      ShippingLine(
        id: 'shp-4',
        name: 'Hapag-Lloyd',
        code: 'HLCU',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      ShippingLine(
        id: 'shp-5',
        name: 'ONE',
        code: 'ONEU',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
    ];
  }

  static List<Location> getLocations() {
    final now = DateTime.now();
    return [
      Location(
        id: 'loc-1',
        name: 'Pune',
        type: LocationType.factory,
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      Location(
        id: 'loc-2',
        name: 'Mumbai',
        type: LocationType.customer,
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      Location(
        id: 'loc-3',
        name: 'Navi Mumbai',
        type: LocationType.warehouse,
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      Location(
        id: 'loc-4',
        name: 'JNPT',
        type: LocationType.port,
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      Location(
        id: 'loc-5',
        name: 'Thane',
        type: LocationType.warehouse,
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      Location(
        id: 'loc-6',
        name: 'Bhiwandi',
        type: LocationType.warehouse,
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      Location(
        id: 'loc-7',
        name: 'Panvel',
        type: LocationType.factory,
        createdAt: now.subtract(const Duration(days: 200)),
      ),
    ];
  }

  static List<PortCfs> getPortCfsList() {
    final now = DateTime.now();
    return [
      PortCfs(
        id: 'pc-1',
        name: 'JNPT Port',
        type: PortCfsType.port,
        location: 'JNPT, Navi Mumbai',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      PortCfs(
        id: 'pc-2',
        name: 'Nhava Sheva CFS',
        type: PortCfsType.cfs,
        location: 'Nhava Sheva, Raigad',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      PortCfs(
        id: 'pc-3',
        name: 'Gateway CFS',
        type: PortCfsType.cfs,
        location: 'Dronagiri, Uran',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
      PortCfs(
        id: 'pc-4',
        name: 'CFS Mumbai',
        type: PortCfsType.cfs,
        location: 'Wadala, Mumbai',
        createdAt: now.subtract(const Duration(days: 200)),
      ),
    ];
  }

  static List<Transport> getTransports() {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);

    return [
      // 1. In Transit (Active today)
      Transport(
        id: 'TR-00124',
        bookingNumber: 'BK2026-8801',
        containerNumber: 'MSCU1234567',
        sealNumber: 'SL-99120',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-1',
        partyName: 'ABC Logistics Pvt Ltd',
        bookingPartyId: 'pty-1',
        bookingPartyName: 'ABC Logistics Pvt Ltd',
        shippingLineId: 'shp-1',
        shippingLineName: 'MSC',
        fromLocationId: 'loc-1',
        fromLocationName: 'Pune',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-1',
        portCfsName: 'JNPT Port',
        vehicleId: 'veh-1',
        vehicleNumber: 'MH12AB1234',
        driverId: 'drv-1',
        driverName: 'Ravi Kumar',
        driverMobile: '9822012345',
        status: TransportStatus.inTransit,
        createdAt: today.add(const Duration(hours: 6)),
        updatedAt: today.add(const Duration(hours: 8)),
      ),

      // 2. Vehicle Assigned (Today)
      Transport(
        id: 'TR-00125',
        bookingNumber: 'BK2026-8802',
        containerNumber: 'MAEU4567890',
        sealNumber: 'SL-99121',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-2',
        partyName: 'XYZ Exports Corp',
        bookingPartyId: 'pty-2',
        bookingPartyName: 'XYZ Exports Corp',
        shippingLineId: 'shp-2',
        shippingLineName: 'Maersk',
        fromLocationId: 'loc-2',
        fromLocationName: 'Mumbai',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-2',
        portCfsName: 'Nhava Sheva CFS',
        vehicleId: 'veh-4',
        vehicleNumber: 'MH48GH3456',
        driverId: 'drv-4',
        driverName: 'Rahul More',
        driverMobile: '9765432109',
        status: TransportStatus.vehicleAssigned,
        createdAt: today.add(const Duration(hours: 7)),
        updatedAt: today.add(const Duration(hours: 7, minutes: 15)),
      ),

      // 3. Vehicle Pending (No suitable vehicle or waiting)
      Transport(
        id: 'TR-00126',
        bookingNumber: 'BK2026-8803',
        containerNumber: 'CMAU9876543',
        sealNumber: 'SL-99122',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.import,
        partyId: 'pty-4',
        partyName: 'Prime Imports Ltd',
        bookingPartyId: 'pty-4',
        bookingPartyName: 'Prime Imports Ltd',
        shippingLineId: 'shp-3',
        shippingLineName: 'CMA CGM',
        fromLocationId: 'loc-4',
        fromLocationName: 'JNPT',
        toLocationId: 'loc-6',
        toLocationName: 'Bhiwandi',
        portCfsId: 'pc-1',
        portCfsName: 'JNPT Port',
        status: TransportStatus.vehiclePending,
        createdAt: today.add(const Duration(hours: 8)),
        updatedAt: today.add(const Duration(hours: 8, minutes: 5)),
      ),

      // 4. Booking Created
      Transport(
        id: 'TR-00127',
        bookingNumber: 'BK2026-8804',
        containerNumber: 'HLCU2345678',
        sealNumber: 'SL-99123',
        containerSize: ContainerSize.size20Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-6',
        partyName: 'Metro Industries',
        bookingPartyId: 'pty-6',
        bookingPartyName: 'Metro Industries',
        shippingLineId: 'shp-4',
        shippingLineName: 'Hapag-Lloyd',
        fromLocationId: 'loc-1',
        fromLocationName: 'Pune',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-3',
        portCfsName: 'Gateway CFS',
        status: TransportStatus.bookingCreated,
        createdAt: today.add(const Duration(hours: 8, minutes: 30)),
        updatedAt: today.add(const Duration(hours: 8, minutes: 30)),
      ),

      // 5. Container Delivered (Waiting POD)
      Transport(
        id: 'TR-00128',
        bookingNumber: 'BK2026-8805',
        containerNumber: 'ONEU3456789',
        sealNumber: 'SL-99124',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-3',
        partyName: 'Global Trading Co.',
        bookingPartyId: 'pty-3',
        bookingPartyName: 'Global Trading Co.',
        shippingLineId: 'shp-5',
        shippingLineName: 'ONE',
        fromLocationId: 'loc-5',
        fromLocationName: 'Thane',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-1',
        portCfsName: 'JNPT Port',
        vehicleId: 'veh-7',
        vehicleNumber: 'MH06NP6789',
        driverId: 'drv-5',
        driverName: 'Vijay Yadav',
        driverMobile: '9860123456',
        status: TransportStatus.containerDelivered,
        createdAt: today.subtract(const Duration(days: 1)),
        updatedAt: today.add(const Duration(hours: 2)),
      ),

      // 6. Completed record 1
      Transport(
        id: 'TR-00120',
        bookingNumber: 'BK2026-8790',
        containerNumber: 'MSCU7766554',
        sealNumber: 'SL-88710',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-1',
        partyName: 'ABC Logistics Pvt Ltd',
        bookingPartyId: 'pty-1',
        bookingPartyName: 'ABC Logistics Pvt Ltd',
        shippingLineId: 'shp-1',
        shippingLineName: 'MSC',
        fromLocationId: 'loc-1',
        fromLocationName: 'Pune',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-1',
        portCfsName: 'JNPT Port',
        vehicleId: 'veh-3',
        vehicleNumber: 'MH04EF9012',
        driverId: 'drv-2',
        driverName: 'Suresh Patil',
        driverMobile: '9822198765',
        status: TransportStatus.completed,
        createdAt: today.subtract(const Duration(days: 2)),
        updatedAt: today.subtract(const Duration(days: 1)),
        completionDate: today.subtract(const Duration(days: 1)),
        pod: PodDocument(
          fileName: 'POD_MSCU7766554_Signed.pdf',
          fileType: 'PDF',
          fileSize: 420100,
          uploadedAt: today.subtract(const Duration(days: 1)),
        ),
      ),

      // 7. Completed record 2
      Transport(
        id: 'TR-00121',
        bookingNumber: 'BK2026-8791',
        containerNumber: 'MAEU3322110',
        sealNumber: 'SL-88711',
        containerSize: ContainerSize.size20Ft,
        shipmentType: ShipmentType.import,
        partyId: 'pty-2',
        partyName: 'XYZ Exports Corp',
        bookingPartyId: 'pty-2',
        bookingPartyName: 'XYZ Exports Corp',
        shippingLineId: 'shp-2',
        shippingLineName: 'Maersk',
        fromLocationId: 'loc-4',
        fromLocationName: 'JNPT',
        toLocationId: 'loc-2',
        toLocationName: 'Mumbai',
        portCfsId: 'pc-2',
        portCfsName: 'Nhava Sheva CFS',
        vehicleId: 'veh-2',
        vehicleNumber: 'MH14CD5678',
        driverId: 'drv-3',
        driverName: 'Amit Sharma',
        driverMobile: '9890145678',
        status: TransportStatus.completed,
        createdAt: today.subtract(const Duration(days: 3)),
        updatedAt: today.subtract(const Duration(days: 2)),
        completionDate: today.subtract(const Duration(days: 2)),
        pod: PodDocument(
          fileName: 'POD_MAEU3322110_Stampted.png',
          fileType: 'IMAGE',
          fileSize: 1850000,
          uploadedAt: today.subtract(const Duration(days: 2)),
        ),
      ),

      // 8. Vehicle Breakdown exception
      Transport(
        id: 'TR-00122',
        bookingNumber: 'BK2026-8792',
        containerNumber: 'CMAU5544332',
        sealNumber: 'SL-88712',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-5',
        partyName: 'Western Cargo Services',
        bookingPartyId: 'pty-5',
        bookingPartyName: 'Western Cargo Services',
        shippingLineId: 'shp-3',
        shippingLineName: 'CMA CGM',
        fromLocationId: 'loc-6',
        fromLocationName: 'Bhiwandi',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-3',
        portCfsName: 'Gateway CFS',
        vehicleId: 'veh-5',
        vehicleNumber: 'MH43JK7890',
        driverId: 'drv-6',
        driverName: 'Sunil Pawar',
        driverMobile: '9922876543',
        status: TransportStatus.vehicleBreakdown,
        exceptionReason: 'Engine overheating near Panvel Highway. Requires replacement vehicle.',
        createdAt: today.subtract(const Duration(days: 1)),
        updatedAt: today.add(const Duration(hours: 1)),
      ),

      // 9. Cancelled record
      Transport(
        id: 'TR-00123',
        bookingNumber: 'BK2026-8793',
        containerNumber: 'ONEU9988776',
        sealNumber: 'SL-88713',
        containerSize: ContainerSize.size20Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-7',
        partyName: 'Apex Manufacturing Co.',
        bookingPartyId: 'pty-7',
        bookingPartyName: 'Apex Manufacturing Co.',
        shippingLineId: 'shp-5',
        shippingLineName: 'ONE',
        fromLocationId: 'loc-7',
        fromLocationName: 'Panvel',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-1',
        portCfsName: 'JNPT Port',
        status: TransportStatus.cancelled,
        exceptionReason: 'Customer cancelled export order due to vessel delay.',
        createdAt: today.subtract(const Duration(days: 4)),
        updatedAt: today.subtract(const Duration(days: 3)),
      ),

      // 10. Container Picked Up
      Transport(
        id: 'TR-00119',
        bookingNumber: 'BK2026-8789',
        containerNumber: 'MSCU6655443',
        sealNumber: 'SL-88709',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-1',
        partyName: 'ABC Logistics Pvt Ltd',
        bookingPartyId: 'pty-1',
        bookingPartyName: 'ABC Logistics Pvt Ltd',
        shippingLineId: 'shp-1',
        shippingLineName: 'MSC',
        fromLocationId: 'loc-1',
        fromLocationName: 'Pune',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-1',
        portCfsName: 'JNPT Port',
        vehicleId: 'veh-11',
        vehicleNumber: 'MH12WX2345',
        driverId: 'drv-7',
        driverName: 'Ganesh Deshmukh',
        driverMobile: '9823456789',
        status: TransportStatus.containerPickedUp,
        createdAt: today.subtract(const Duration(days: 1)),
        updatedAt: today.subtract(const Duration(hours: 3)),
      ),

      // 11. At Port / CFS
      Transport(
        id: 'TR-00118',
        bookingNumber: 'BK2026-8788',
        containerNumber: 'HLCU1122334',
        sealNumber: 'SL-88708',
        containerSize: ContainerSize.size40Ft,
        shipmentType: ShipmentType.export,
        partyId: 'pty-8',
        partyName: 'Blue Star Freight Forwarders',
        bookingPartyId: 'pty-8',
        bookingPartyName: 'Blue Star Freight Forwarders',
        shippingLineId: 'shp-4',
        shippingLineName: 'Hapag-Lloyd',
        fromLocationId: 'loc-3',
        fromLocationName: 'Navi Mumbai',
        toLocationId: 'loc-4',
        toLocationName: 'JNPT',
        portCfsId: 'pc-1',
        portCfsName: 'JNPT Port',
        vehicleId: 'veh-9',
        vehicleNumber: 'MH15ST4567',
        driverId: 'drv-8',
        driverName: 'Deepak Shinde',
        driverMobile: '9730012345',
        status: TransportStatus.atPortCfs,
        createdAt: today.subtract(const Duration(days: 2)),
        updatedAt: today.subtract(const Duration(hours: 5)),
      ),

      // 12. POD Received (Ready to be Completed)
      Transport(
        id: 'TR-00117',
        bookingNumber: 'BK2026-8787',
        containerNumber: 'MAEU8877665',
        sealNumber: 'SL-88707',
        containerSize: ContainerSize.size20Ft,
        shipmentType: ShipmentType.import,
        partyId: 'pty-4',
        partyName: 'Prime Imports Ltd',
        bookingPartyId: 'pty-4',
        bookingPartyName: 'Prime Imports Ltd',
        shippingLineId: 'shp-2',
        shippingLineName: 'Maersk',
        fromLocationId: 'loc-4',
        fromLocationName: 'JNPT',
        toLocationId: 'loc-6',
        toLocationName: 'Bhiwandi',
        portCfsId: 'pc-2',
        portCfsName: 'Nhava Sheva CFS',
        vehicleId: 'veh-6',
        vehicleNumber: 'MH01LM2345',
        driverId: 'drv-9',
        driverName: 'Pravin Jadhav',
        driverMobile: '9881123456',
        status: TransportStatus.podReceived,
        createdAt: today.subtract(const Duration(days: 2)),
        updatedAt: today.subtract(const Duration(hours: 1)),
        pod: PodDocument(
          fileName: 'POD_MAEU8877665_Delivered.pdf',
          fileType: 'PDF',
          fileSize: 310500,
          uploadedAt: today.subtract(const Duration(hours: 1)),
        ),
      ),
    ];
  }

  static List<ActivityLog> getActivityLogs() {
    final now = DateTime.now();
    return [
      ActivityLog(
        id: 'act-1',
        transportId: 'TR-00124',
        title: 'Booking Created',
        description: 'New booking registered for container MSCU1234567',
        timestamp: now.subtract(const Duration(hours: 8)),
      ),
      ActivityLog(
        id: 'act-2',
        transportId: 'TR-00124',
        title: 'Vehicle Assigned',
        description: 'Assigned Trailer MH12AB1234 (40 FT)',
        timestamp: now.subtract(const Duration(hours: 7, minutes: 55)),
      ),
      ActivityLog(
        id: 'act-3',
        transportId: 'TR-00124',
        title: 'Driver Assigned',
        description: 'Assigned Driver Ravi Kumar (9822012345)',
        timestamp: now.subtract(const Duration(hours: 7, minutes: 55)),
      ),
      ActivityLog(
        id: 'act-4',
        transportId: 'TR-00124',
        title: 'Customer Notification Sent',
        description: 'WhatsApp assignment dispatch notification sent to customer',
        timestamp: now.subtract(const Duration(hours: 7, minutes: 50)),
      ),
      ActivityLog(
        id: 'act-5',
        transportId: 'TR-00124',
        title: 'Trip Started: In Transit',
        description: 'Vehicle reported at Pune factory & departed for JNPT',
        timestamp: now.subtract(const Duration(hours: 6)),
      ),
    ];
  }

  static List<NotificationLog> getNotificationLogs() {
    final now = DateTime.now();
    return [
      NotificationLog(
        id: 'notif-1',
        transportId: 'TR-00124',
        recipientName: 'ABC Logistics Pvt Ltd',
        recipientMobile: '9822001122',
        channel: 'WhatsApp',
        messageBody:
            'Dear Customer,\n\nYour transport vehicle has been assigned.\n\nVehicle No: MH12AB1234\nContainer No: MSCU1234567\nDriver Name: Ravi Kumar\nDriver Contact: 9822012345\nFrom: Pune\nTo: JNPT\nBooking No: BK2026-8801\n\nThank you.',
        status: 'SENT',
        sentAt: now.subtract(const Duration(hours: 7, minutes: 50)),
      ),
    ];
  }
}
